### ISSUE TITLE
Can't raise issue for `soulutf8`

### ISSUE THREAD

**Issue by kpym** [ho-tex/soul#1]
I know that the package [soulutf8](https://github.com/ho-tex/soul) is not part of this bundle, but because it was originally created by Heiko Oberdiek and is part of `ho-tex` I point here that the issues are disabled for this GitHub repo, so I can't raise an issue for it.
By the way, CTAN points to `https://github.com/ho-tex/soul/issues` which is not available.

Is this intentional ? If so, where I can report a problem regarding this package ?

**Comment by davidcarlisle** [comment]
@kpym  thank you for the notice. For reasons that are not entirely clear this repository was set up as a fork of soul rather than being a new self-standing soulutf8 repository. By default github disables issues on forks and until your comment I hadn't noticed that issues were disabled.  I have enabled issues and transferred this issue here to

https://github.com/ho-tex/soul/issues/1

**Comment by kpym** [comment]
@davidcarlisle Thank you for considering my request and for your quick response.
