### ISSUE TITLE
Soul sets page number to zero when highlighted text has more than 2 paragraphs and crosses pages

### ISSUE THREAD

**Issue by xexeo** [ho-tex/soul#4]
Hi,

  Soul sets page number to zero when highlighted text has more than 2 paragraphs and crosses pages.

  It does not reset if one single paragraph cross pages.

 I included a minimal example and a pdf showing the problem. I needed 3 pages to correctly show the bug.
  
[soulbug.zip](https://github.com/ho-tex/soul/files/7984020/soulbug.zip)
[soulbug.pdf](https://github.com/ho-tex/soul/files/7984021/soulbug.pdf)

 I am using soul in [coop-writing](https://www.ctan.org/pkg/coop-writing), recently added in CTAN. It was very practical, but a user found the bug and complained to me, and I traced it to the \hl command.

 Thanks for your help.

**Comment by u-fischer** [comment]
Side remark: Your document doesn't compile due to the non-ascii chars, it would need soulutf8.  

But beside this: the situation is a bit complicated. This here is not the github for soul but for soulutf8, an extension to support utf8. Your issue has already been reported in the original github for soul https://github.com/drehscheibe/soul/issues/2, and so how to fix it is known. 

We are considering to merge soul and soulutf8 (https://github.com/drehscheibe/soul/issues/4) and then both packages would get the fix.

**Comment by xexeo** [comment]
The bug happens in both soul and soulutf8, but it seems to me that there is no problem in using soul in LuaLaTeX with UTF8, as I´ve been doing it.

**Comment by u-fischer** [comment]
The problem has been resolve in version 3.0. so I'm closing this.
