### ISSUE TITLE
! Package soul Error: Reconstruction failed.

### ISSUE THREAD

**Issue by XiangyunHuang** [ho-tex/soul#9]
Do you have any plan to support Chinese?

```tex
\documentclass{article}
\usepackage{ctex}
\usepackage{soul}
\begin{document}
\st{中文}  % Here are two CJK characters
\end{document}
```

When I try to compile using XeLaTeX, an error happens as follow:

! Package soul Error: Reconstruction failed.

**Comment by u-fischer** [comment]
I doubt that it will ever work. The problem is not the Chinese in itself but all the additional code that ctex inserts (boxes and font hooks and more) and which confuses the soul package. Without ctex it more or less works, if one set the font correctly:

~~~~
\documentclass{article}
%\usepackage[fontset=fandol]{ctex}
\usepackage{soul}
\usepackage{fontspec}
\setmainfont{FandolSong-Regular.otf}
\setmonofont{FandolSong-Regular.otf}
\makeatletter 
\setbox\z@\hbox{\ttfamily\global\let\SOUL@tt\ttfamily}
\setbox\z@\hbox{\SOUL@tt-}
\SOUL@ttwidth\wd\z@
\makeatother
\begin{document}
\st{中文} % Here are two CJK characters
\end{document}
~~~~

I would suggest to use lualatex and the lua-ul package instead. That is much less fragile:

~~~~
\documentclass{article}
\usepackage[fontset=fandol]{ctex}
\usepackage[soul]{lua-ul}
\begin{document}
\st{中文}  % Here are two CJK characters
\end{document}
~~~~

![image](https://github.com/ho-tex/soul/assets/4047173/c3bb8fb0-5c20-4825-8e82-40ff0828103a)

**Comment by mbertucci47** [comment]
There is also the `xeCJKfntef` package for xelatex, documented in [`xeCJK`](http://mirrors.ctan.org/macros/xetex/latex/xecjk/xeCJK.pdf)

**Comment by XiangyunHuang** [comment]
Thank you for letting me know more and deeper about soul.
